### ISSUE TITLE
Plot not updating when using serial stream in Histogram Mode

### ISSUE THREAD

**Issue by acunipisa** [OpenGammaProject/Gamma-MCA#197]
Hi,

Firstly, I want to extend my congratulations on the exceptional work done here. This tool serves as a fantastic interface for open-source or DIY gamma spectrometers.

I have tested the Chrome-based version of the software and found it performs efficiently in chronological mode. However, I encountered an issue in histogram mode: the plot fails to refresh with the arrival of new data.

I've provided the settings I'm utilizing below. Notably, the serial data stream is accurately displayed in the console.

![gammaMCA_settings](https://github.com/OpenGammaProject/Gamma-MCA/assets/122541422/a27b0dd6-fbec-44bd-8831-36d583cd6856)

As a tester, I am using an esp32 with the following code (Arduino IDE 2.2.1):
```
uint16_t spectrum_1[256];
String spectrumStr;

void setup() {
  Serial.begin(9600);
  for (uint16_t i = 0; i < 256; i++) {
    spectrum_1[i] = 1;
  }

}

void loop() {
  spectrumStr = "";
  for (uint16_t i = 0; i < 256; i++) {
    //Serial.print(spectrum_1[i]); Serial.print(";");
    spectrumStr += "1";
    spectrumStr += ";";
  }
  Serial.println(spectrumStr);
  delay(3000);
}
```
The stream of 1s is correctly shown in the console, but the plot and cts do not reflect this. What am I missing?

Thanks for your support,
Andrea

**Comment by NuclearPhoenixx** [comment]
Hi, 

firstly, thanks for the kind words!

One reason I can think of why it isn't working is because the `spectrumStr` doesn't have the right length. It needs to have exactly 256 bins with your settings, but in your sketch it only seems like it's appending more and more data without actually removing old data.

If you know how to open the dev console in Chrome that would also be very helpful as there might be a more verbose error message there.

Thanks.

**Comment by NuclearPhoenixx** [comment]
>  I will keep the whole spectrum in the esp32 memory, and stream it through serial when needed.

Yeah exactly, just keep the whole spectrum and update values as you go. No need to do any more computing.

> I opened the dev console in chrome, and the only line returned was an "Invalid sum range! return default 0"

That's okay, that warning pops up whenever you don't have the full spectrum **and** the background spectrum loaded, i.e. both. You can ignore it, it's nothing worth noting.

> Anyway now it works beautifully, thank you for you support.

Perfect, glad I could help. I'm closing this issue then.
